# Generated by Django 4.0.2 on 2022-05-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_colormodel_sizemodel_productmodel_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
    ]
